### ISSUE TITLE
No react-router-native module.

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/Ptt-RN#5]
in iOS:

![image](https://user-images.githubusercontent.com/2970164/135867370-2d11d77a-de11-4821-a0b9-b5cd6b5f9f01.png)

It seems like i18n-js and react-router-native are not compatible?

Does that mean we need to change our react-router settings if we want to use i18n-js?

**Comment by urakagi** [comment]
I believe it's just a `package.json` error. I don't see `react-router-native` in it. I'll fix it.

**Comment by urakagi** [comment]
Find other problems on an Android simulator. Will reopen after solving.

**Comment by urakagi** [comment]
Close wrong place, meant to close PR.

**Comment by chhsiao1981** [comment]
https://github.com/Ptt-official-app/Ptt-RN/blob/main/App.js#L8
https://github.com/Ptt-official-app/Ptt-RN/blob/main/src/i18n.js#L3
https://github.com/Ptt-official-app/Ptt-RN/blob/main/src/i18n.js#L23

Is it that expo compiler get confused with RNLocalize?

Or we should all use import instead of require?

**Comment by chhsiao1981** [comment]
Looks like something went wrong with react-native-localize vs. expo.
In that:

1. react-native-localize asks to do pod install, while there is no "pod install" in expo.
    https://github.com/zoontek/react-native-localize

2. expo itself seems to be an emulator inside iOS / Android, it's possible that react-native-localize can't recognize whether expo is iOS/Android/Web.

TODO:
1. remove i18n for now.
2. rename project as PttRN, due to requirement from react-native-cli that project is alpha-number only.
2. try another branch with react-native-cli and see whether react-native-localize can work.

**Comment by chhsiao1981** [comment]
#8 shows that react-native-cli can work with react-native-localize and react-router-native well.

The good part of react-native-cli also includes that:
1. the version of react-native can be much more up-to-date～
2. We don't need to depend on expo for building the app～

**Comment by chhsiao1981** [comment]
#8 resolves this issue.
